### ISSUE TITLE
Sammelticket für Layout-Bugs

### ISSUE THREAD

**Issue by fluetze** [ub-duisburg-essen/ubo-due#2]
1. Seitentitel und Breadcrumb: Avatar-Kreis fehlt, Trenner zwischen Breadcrumb-Items fixen, vgl. https://www.uni-due.de/ub/abisz/literaturverwaltung.shtml
2. Sprachumschaltung: Icons verschwinden wenn Seite nicht auf Root-Ebene ist, z. B. Trefferliste (/servlets/solr/*)
3. Trefferliste> Facetten-Bezeichnungen: lange Labels brechen um in neue Zeile, overflow:hidden oder bei mouseover anzeigen? -> [UBO-61](https://mycore.atlassian.net/browse/UBO-61)
4. Detailansicht Einzeltreffer: div mit Badges (Publikationstypen usw) hat kein Padding -> [UBO-62](https://mycore.atlassian.net/browse/UBO-62)
5. Startseite, als Admin, Facetten Publikationen nach Status usw: nicht gut als Links erkennbar -> [UBO-63](https://mycore.atlassian.net/browse/UBO-63)
6. Repeater-Buttons: sind zu groß, brechen um in neue Zeile wenn mehr als 3 -> [UBO-64](https://mycore.atlassian.net/browse/UBO-64)
7. Detailansicht, Ausgabe Abstract: wird nicht abgesetzt, kein Padding -> [UBO-65](https://mycore.atlassian.net/browse/UBO-65)

**Comment by kkrebs** [comment]
Punkt 2 scheint nicht mehr aufzutreten in der aktuellen Version, zumindest konnte ich den Fehler lokal nicht reproduzieren. Bei den anderen Punkten prüfen wir, was davon besser direkt in der UBO gefixt werden sollte. Mir scheint 3-7 könnte das betreffen. Bleibt erstmal akut in diesem Ticket der 1. Punkt als ToDo für ubo-due.

**Comment by TiloNN** [comment]
Habe Punkt 1 bearbeitet und ein pull request erstellt.

**Comment by kkrebs** [comment]
Habe nun wie besprochen aus den Punkten 3-7 UBO-Tickets gemacht:
- [UBO-61](https://mycore.atlassian.net/browse/UBO-61)
- [UBO-62](https://mycore.atlassian.net/browse/UBO-62)
- [UBO-63](https://mycore.atlassian.net/browse/UBO-63)
- [UBO-64](https://mycore.atlassian.net/browse/UBO-64)
- [UBO-65](https://mycore.atlassian.net/browse/UBO-65)

**Comment by TiloNN** [comment]
Habe die fünf Punkte bearbeitet.
Kann nur der Anfang sein.
